### ISSUE TITLE
Support for $ref elements

### ISSUE THREAD

**Issue by piersmacdonald** [WindomZ/swagger-merger#28]
Love the package, it would be great to see it support references to sub elements of a file. Documentation:

https://swagger.io/docs/specification/using-ref/

example

`$ref: '../document.json#/myElement'`

**Comment by WindomZ** [comment]
@piersmacdonald 
Thank you for your suggestion, that`s a good supplement!

I've provided an [implementation](https://github.com/WindomZ/swagger-merger/commit/1724bc86d96c93ba6f5c3877b8f9bc4c0815bf4a).
