### ISSUE TITLE
Windows support for splitReference method

### ISSUE THREAD

**Issue by adamzoltan873** [WindomZ/swagger-merger#32]
Hi WindomZ,

First of all, nice work :)
...And then the issue:

On Windows, when you evaluate path.join() the structure will be converted
./responses.yaml#/components/root/get -> .\responses.yaml#\components\root\get

This is Ok, if you want to locate the file, but the splitReference method gets the \components\root\get string so this code is not enugh

```
if (hashtag.startsWith('/')) {
          hashtag = hashtag.slice(1)
        }
```
I would suggest place these 2 lines before this:

```
//in case of windows operating system
hashtag = hashtag.replace(/\\/g, "/")
```

Regards, Adam

**Comment by WindomZ** [comment]
@adamzoltan873  Thank you!

It`s OK in the virtual machine.

**Comment by WindomZ** [comment]
Welcome your [PR](https://github.com/WindomZ/swagger-merger/pulls) next time.
