### ISSUE TITLE
reference remote files 

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [WindomZ/swagger-merger#36]
i would like to merge a remote file like 
`$ref: "https://raw.githubusercontent.com/swagger-api/swagger-codegen/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml"` into my specification and also use the `url#/subobject` syntax on it like:
`$ref: "https://raw.githubusercontent.com/swagger-api/swagger-codegen/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#/securityDefinitions"`
Is it possible to implement this for swagger-merger?

**Comment by WindomZ** [comment]
Good idea :+1: , I tried to implement this idea in v1.3.0

Welcome feedback.

**Comment by TheGreatRefrigerator** [comment]
Hi @WindomZ ,
thank you for such a fast fix, again :+1: 
Sadly it's not working for me this time.

doesn't matter where i try to reference, i always get this error for the following merge using the newest 1.3.0:

$ `node_modules/swagger-merger/bin/swagger-merger.js -i index.yaml -o test.yaml --debug`

I tried it on my own file as well as this [index.yaml](https://github.com/WindomZ/swagger-merger/blob/master/example/petstore_domain/index.yaml) from the examples without the local references (paths, definitions)

```
SyntaxError: Unexpected token U in JSON at position 271
    at Object.parse (native)
    at mergeJSON (..\node_modules\swagger-merger\lib\merge_json.js:26:15)
    at mergerYAML (..\node_modules\swagger-merger\lib\merger_yaml.js:20:13)
    at merge (..\node_modules\swagger-merger\lib\merger.js:52:14)
    at merger (..\node_modules\swagger-merger\lib\merger.js:34:3)
    at next (native)
    at onFulfilled (..\node_modules\co\index.js:65:19)
    at ..\node_modules\co\index.js:54:5
    at co (..\node_modules\co\index.js:50:10)
    at createPromise (..\node_modules\co\index.js:30:15)
```

might be something like [this](https://stackoverflow.com/questions/13022178/uncaught-syntaxerror-unexpected-token-u-json)
But i didn't understand completely what is happening in lines 26 and 27 of merge_json.js

**Comment by TheGreatRefrigerator** [comment]
I tested it today on a fresh new linux installation (other was with windows in gitbash where i often run into some problems).
It worked fine :)

**Comment by WindomZ** [comment]
I have found some problems in Windows
