### ISSUE TITLE
requires file extension

### ISSUE THREAD

**Issue by chrisdostert** [WindomZ/swagger-merger#40]
## expected
referencing a remote yaml or json file with or without a file extension works the same

## actual
if the remote file doesnt have a file extension the cli replaces the reference with `undefined` instead of dereferencing the remote file

**Comment by WindomZ** [comment]
Thank you for your feedback. I think this issue has been corrected in #41 .

**Comment by chrisdostert** [comment]
@WindomZ thank you so much for looking at this so fast. That doesn't seem to have fixed it, only changed it to a different behavior. Now what's happening is no replacements are happening at all for those references, they just stay there unmodified. 

this is an example:
```yaml
paths:
  $ref#users-api: https://api.eraofhealth.com/users-api#paths
```

**Comment by WindomZ** [comment]
Thanks for this example.

This remote address is not a JSON suffix file, so tool ignores this.

I create a feature issue #42.
This feature will be added to the next version.

**Comment by WindomZ** [comment]
I submitted, welcome feedback or submit test cases.

**Comment by chrisdostert** [comment]
@WindomZ You rule!

I think I found a bug w/ the implementation.

if I use the reference
```yaml
paths:
  $ref#users-api: https://api.eraofhealth.com/users-api#paths
```
it will de-reference the document now but it dereferences the entire document, not only `#paths`

**Comment by WindomZ** [comment]
Try again after updating

**Comment by chrisdostert** [comment]
working great, I appreciate it!
