### ISSUE TITLE
$ref partially expanded in included files

### ISSUE THREAD

**Issue by humpfhumpf** [WindomZ/swagger-merger#52]
If you merge the attached sample.yaml, "#/definitions/Code" is not expanded.

[sample.zip](https://github.com/WindomZ/swagger-merger/files/2420553/sample.zip)

Regards

**Comment by WindomZ** [comment]
`swagger-merger` is a tool to merge multiple files into one file, support remote files.

About `Local Reference` like so: ` – $ref: '#/definitions/myElement'`, with official support, the tool will not be repeated :smile: .
