### ISSUE TITLE
Replacing the input swagger file with the output swagger file (not merging)

### ISSUE THREAD

**Issue by NikhilNanjappa-zz** [WindomZ/swagger-merger#56]
If I run the command

```
swagger-merger -i petstore.json -o myswagger.json
```

### Expected
The content of `petstore.json` gets **merged/combined** into content of `myswagger.json`, meaning `myswagger.json` **should have both**.

### Issue
The content of `petstore.json` **overwrites/replaces** the content of `myswagger.json`, meaning the content of `myswagger.json` is lost!

**Comment by WindomZ** [comment]
The design idea is only one in '-i' and one out '-o', overwrite the output file. :)

**Comment by WindomZ** [comment]
You have suggested supporting multiple input files. Also welcome PR

**Comment by ylacaute** [comment]
I just discovered this tools and I read "Merge multiple swagger files into a swagger file" but I don't undertstand how it works. I expected to use the "-i" option many time, otherwise I dont understand the interest of this tool : my generated output is exactly the same as my input.

**Comment by scaothanhson** [comment]
Me too. Although I used "-i" option many time, it returned content of first file. Cannot merger many file, only replace.
What does "merger" mean?

**Comment by MikeChristensen** [comment]
Agreed, it's unclear what this tool actually does.   I was trying to create a single YAML file that references a bunch of other YAML files, and then merge them into one giant YAML files with all the APIs in one.  I wasn't able to get anything working.  What exactly does this tool do?

**Comment by NikhilNanjappa-zz** [comment]
If anyone is looking for an actual merge/combine tool, try this - https://www.npmjs.com/package/swagger-combine instead.

I used this sometime back and worked fine for me. If my memory serves right, you might have to create a config file and mention the files to be combined in it before running the combine command etc. There are alternate ways to combine as well which could be mentioned in the docs. Worth a shot!

**Comment by MikeChristensen** [comment]
Thanks @NikhilNanjappa  that looks like exactly what I was looking for!

**Comment by ericcarino** [comment]
Adding my input to help clear some confusion.  I have 5 swagger files I'm trying to merge to one.  I just repeat the following command for each file.

`swagger-merger -i source1.yaml -o target.yaml `

This mostly works great and I'm able to merge 4 of the 5 files.  For some reason, the 5th file doesn't merge properly and simply replaces the whole target file.  I suspect a bug here, so continuing to debug.

**Comment by WindomZ** [comment]
The design of `swagger-merger`: 
**Merge** multiple **related** files from **one** input file into **one** output file and **overwrite** it, **not** multiple **unrelated** files.
> How to relate？ Use `$ref` or `$ref#*`
