### ISSUE TITLE
Merging content from files does not working well on a special situation

### ISSUE THREAD

**Issue by ibucur** [WindomZ/swagger-merger#61]
I am having the following files:

[testBug.zip](https://github.com/WindomZ/swagger-merger/files/3019593/testBug.zip)

The idea is: in the command description file, for some reasons, the same uri is expanded into 2 different path locations (one is for global access and will be included in one documentation and the second one is for admin and will be included in the admin documentation along with the one from global).

The idea is when merging the files swagger-merger -i ./test-spec.json -o ./test.json, the resulted file contains just one command for the given endpoint (jut put without get) if the same endpoint is found 2 times. 
It does not work well even if I change the tags and I name them differently.

If you need more details, just let me know. This feature saves us on big projects with lots of api endpoints to manage in a documentation which is splitted into different small files for easily management.

Regards

**Comment by WindomZ** [comment]
In the '`test-spec.json`' file you provided, I think the following example will generate the result you expect:
![image](https://user-images.githubusercontent.com/14875359/153742924-50aaed08-8735-4c34-84ec-b8ddb75be046.png)
