### ISSUE TITLE
Run inside JavaScript

### ISSUE THREAD

**Issue by andrewright** [WindomZ/swagger-merger#66]
How can i run ir inside javascript code not user **child_process exec** and not install globally?

const swaggerMerger = require('swagger-merger');
swaggerMerger  ....

**Comment by WindomZ** [comment]
I think the following example is what you want:

```js
const swaggerMerger = require('swagger-merger')

swaggerMerger.merge({
  input: 'index.json',
  output: 'swagger.json',
  compact: false
}).catch(e => {
  console.error(e)
})
```
is it?
