### ISSUE TITLE
Referencing a file with paths adds quotes around every path

### ISSUE THREAD

**Issue by daynejones** [WindomZ/swagger-merger#67]
Reference:
```
# main.yaml
paths:
  $ref#reconciliation: "./reconciliation.yaml"
...
```

```
# reconciliation.yaml
/mypath/{id}:
 post:
...
```

result
```
# swagger.yaml
paths:
  '/mypath/{id}':
 post:
...
```

The quotes around the path seem to be invalid.

**Comment by WindomZ** [comment]
I get the following result:
```yml
paths:
  /mypath/{id}:
    post: null
```
Also, according to [YAML v1.2 spec](https://yaml.org/spec/1.2.2/):
> 10.3.2. Tag Resolution
> 
> ```
> Regular expression         Resolved to tag
> null | Null | NULL | ~     tag:yaml.org,2002:null
> /* Empty */                tag:yaml.org,2002:null
> ```

`null` or `~` or `omitting value` produces the same result: `tag:yaml.org,2002:null`
