### ISSUE TITLE
How about adding Dockerfile and publishing images on DockerHub?

### ISSUE THREAD

**Issue by ohbarye** [WindomZ/swagger-merger#69]
Hello  👋 
As the title says, how about adding Dockerfile and publishing images on DockerHub?

I use swagger-merger with Docker. It compels me to write a Dockerfile for that but it brings a benefit to reuse this library with ease.

I've already created an example repository https://github.com/ohbarye/swagger-merger-docker and published Docker image on https://hub.docker.com/r/ohbarye/swagger-merger though, I think the Dockerfile can be in this repository (if you're willing so).

If you don't like this idea, feel free to close this issue. I know that managing a Docker image needs additional works and a maintainer might suffer.

**Comment by WindomZ** [comment]
Well done, this is what I hope, thank you for your contribution!

**Comment by ohbarye** [comment]
Thanks for your opinion, I created a pull request #70 for that.
